###
# TODO: install redis server in masters. http://redis.io/topics/quickstart
# TODO: change bind_ip in my.cnf and mongo.cnf
# TODO: setup ssh-keys between servers, worker->master,mongo --- master->mongo
####



# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts

- hosts: all
  roles:
    - common


- include: workers.yml
# - include: masters.yml
# - include: distributor.yml
# - include: mongo.yml
# - include: aws.yml
