# MySQL

- name: install MySQL
  apt: name="{{ item }}" state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
    - php5-mysql

- name: add mysql user
  mysql_user: name=auditor host="{{ item }}" password=yb9738z priv=*.*:ALL,GRANT login_user=root login_password=
  with_items:
    - '%'
    - localhost

- name: make sure mysql is running
  action: service name=mysql state=started enabled=true


# disable bind_address to enable remote connections
- name: change bind_address in my.cnf
  lineinfile: dest=/etc/mysql/my.cnf regexp='bind-address\s*=\s*127\.0\.0\.1\s*' line='bind-address   = 0.0.0.0' state=present backrefs=yes

- service: name=mysql state=restarted


# remove database if exist, insert new data
- name: delete database first
  mysql_db: name="{{ item }}" state=absent login_user=auditor login_password=yb9738z
  with_items:
    - auditor_temp

# create mysql DBs
- name: create mysql databases
  mysql_db: name="{{ item }}" state=present login_user=auditor login_password=yb9738z
  with_items:
    - auditor_distributed


# Copy database dump file to remote host and restore it to database
- copy: src=/home/sachin/Documents/Server_Setups/ansible_config/files/auditor_distributed.sql dest=/tmp
- mysql_db: name=auditor_distributed state=import target=/tmp/auditor_distributed.sql  login_user=auditor login_password=yb9738z

